spring.datasource.url=jdbc:mysql://localhost:3306/agroroot
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=DB_PassWord
=======
spring.datasource.password=DB-PASSWORD
>>>>>>> fcbde8e (Updated complete project)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
